### ISSUE TITLE
What does the FACTOR in post_processing_viz() do and how well does it work?

### ISSUE THREAD

**Issue by BillSiriusLiu** [TommyZihao/vlm_arm#1]
Great work!

In the examples given in SYSTEM_PROMPT, the coordinates of the bounding box corners is out of range, since the input image is 640*480. And function post_processing_viz() uses a FACTOR equals to 999 to normalize the output coordinates from the LLM, **I guess**. 

However, since the range of coordinates are not specified in SYSTEM_PROMPT, what if the output coordinates are larger than 999? Did this ever happen in your experiments? 

And how well does this FACTOR works? For the vl_now_viz.jpg shows the bounding box of Li Yunlong is actually not accurate.

Also, why is the FACTOR set to 999? Is this an empirical design or does it has something to do with the LLM used? 

Thank you for your excellent work again and looking forward to your reply!

**Comment by TommyZihao** [comment]
hi, this factor is from https://github.com/01-ai/Yi/issues/376
Only fit for Yi-Vision API

**Comment by BillSiriusLiu** [comment]
> hi, this factor is from [01-ai/Yi#376](https://github.com/01-ai/Yi/issues/376)
> Only fit for Yi-Vision API

Thanks for your kind reply! 

It might have something to do with their preprocessing but no details are provided. In [https://huggingface.co/01-ai/Yi-VL-34B](url) the image is resized to 448×448. The 999 just comes out of nowhere. 

Strange but no matter, as long as it works fine.

**Comment by TommyZihao** [comment]
> > hi, this factor is from [01-ai/Yi#376](https://github.com/01-ai/Yi/issues/376)
> > Only fit for Yi-Vision API
> 
> Thanks for your kind reply!
> 
> It might have something to do with their preprocessing but no details are provided. In [https://huggingface.co/01-ai/Yi-VL-34B](url) the image is resized to 448×448. The 999 just comes out of nowhere.
> 
> Strange but no matter, as long as it works fine.

Yes, I have talked to a guy from Yi, he said they will launch a new Yi-Vision model next month(maybe end of June)
