### ISSUE TITLE
utils_vlm.py 中返回描述物体的像素位置，返回的坐标都是错乱的

### ISSUE THREAD

**Issue by ovjust** [TommyZihao/vlm_arm#3]
而且我尝试问它 图片的分辨率，某个坐标处是什么物体，给出的答案都是错误的
![image](https://github.com/TommyZihao/vlm_arm/assets/12697538/23d692dd-6898-4b01-b650-6b434ce02bbe)

**Comment by TommyZihao** [comment]
需要做坐标转换
https://github.com/01-ai/Yi/issues/376
