### ISSUE TITLE
utils_vlm.py中的缩放因子为什么是999

### ISSUE THREAD

**Issue by LUORANCHENG** [TommyZihao/vlm_arm#4]

**Comment by TommyZihao** [comment]
https://github.com/01-ai/Yi/issues/376
零一万物的官方提供的，我也不知道为啥

**Comment by TommyZihao** [comment]
![image](https://github.com/TommyZihao/vlm_arm/assets/36354458/960f8db4-19b5-47b0-bf12-6d2fcdcf1e72)
