### ISSUE TITLE
AttributeError: module 'appbuilder' has no attribute 'ASR'

### ISSUE THREAD

**Issue by yangle9567** [TommyZihao/vlm_arm#5]
下载的appbuilder 依赖模块无法正常使用，难道不是这样下载的吗  pip install appbuilder

**Comment by TommyZihao** [comment]
需要python3.9以上版本才行，百度那边的问题

**Comment by zhu-peiqi** [comment]
我python3.10也是出现这样的问题

**Comment by TommyZihao** [comment]
> 我python3.10也是出现这样的问题

用python3.12

**Comment by TommyZihao** [comment]
> 下载的appbuilder 依赖模块无法正常使用，难道不是这样下载的吗 pip install appbuilder

python 3.12 
pip install appbuilder-sdk
