### ISSUE TITLE
hi, 请问这个demo里面有手眼标定代码吗

### ISSUE THREAD

**Issue by lovegit2021** [TommyZihao/vlm_arm#6]
hi, 大佬，请问这个demo里面有手眼标定代码吗

**Comment by TommyZihao** [comment]
https://github.com/TommyZihao/vlm_arm/blob/main/%E5%85%B6%E5%AE%83%E8%BE%85%E5%8A%A9%E4%BB%A3%E7%A0%81/%E3%80%90K3%E3%80%91%E6%89%8B%E7%9C%BC%E6%A0%87%E5%AE%9A.ipynb

谢谢提醒，我刚刚上传了
